### ISSUE TITLE
Long parsing time

### ISSUE THREAD

**Issue by x-raizor** [UptakeOpenSource/uptasticsearch#80]
Taking minutes for data scrolling (OK) and tens and twenties of minutes for parsing (very strange) for 700-800K of documents. 

I tried to keep only plain (not nested) fields. 4-5 fields for the document.  

Here was at least one observation when for the same request I had such long situation but after updating the library the same request was processed with in minutes (OK). 

I can’t realize which data to put here for represent the issue. Any thoughts?

I am using the latest version of uptasticsearch now but the strange behavior is repeating. 

Is it known behavior? 
How should I avoid it?

**Comment by jameslamb** [comment]
Hello @x-raizor . Thanks for using `uptasticsearch`! We're happy to help you out, but need some more details.

Can you elaborate on this sentence:

> after updating the library the same request was processed with in minutes (OK)

Does that mean that the issue is now fixed on `uptasticsearch v0.3.0` (the most current one on CRAN)?

I understand that you probably can't share your data with us, but can you share the query and the `uptasticsearch` call you're using? Maybe we can help tune the query by visual inspection

**Comment by x-raizor** [comment]
Hello @jameslamb, thank you for quick reply and for the such great library!

Unfortunately, I see the problem on my side with the latest version 0.3.0. I wrote that the library updating fixed the problem once with certain query. But now I see the same problem with other request. 

Last time parsing phase lasts 3 hours before I interruped it :-( 
After relaunch it ended perfectly =\

Here is request and uptasticsearch call code:

```
query <- '
{
    "query": {
        "bool": {
            "must": [
                {
                    "terms": {
                        "event": [
                            "product_card_view"
                            ]
                    }
                },
                {
                    "exists": {
                        "field": "delivery_types.crosses"
                    }
                },
                {
                    "multi_match": {
                        "query": "ТСП NOT Росско",
                        "fields": [
                            "delivery_types.product",
                            "delivery_types.crosses"
                            ]
                    }
                }
                ]
        }
    },
    "_source": [
        "delivery_types.crosses",
        "delivery_types.product",
        "product_groups_stats.crosses.fastest_delivery_visible",
        "product_groups_stats.crosses.fastest_delivery_included_nested",
        "product_groups_stats.product.fastest_delivery_visible",
        "product_groups_stats.product.fastest_delivery_included_nested"
    ]
}
'

test_df <- es_search(es_host, "cart_item_event-*", query_body = query)
```

**Comment by jameslamb** [comment]
Is it possible to share a log? I'm wondering if the issue is in "parsing" or in actually pulling records from the network. This query is hitting multiple indices and doing a somewhat costly query (`multi_match`), so I'm wondering if the root issue here is the performance of your cluster / network and not the library itself.

Also, we have never tested using a wildcard `*` to select multiple indices, so it's very possible that something in the way we've set up the library is inefficient for that query pattern. I'm really interested in getting to the bottom of this!

**Comment by x-raizor** [comment]
@jameslamb for now I can't reproduce such situations. I will bring details as soon as I will get long delays again.

**Comment by jameslamb** [comment]
@x-raizor checking back in on this. Have you been using `uptasticsearch`? Has this problem persisted?

**Comment by x-raizor** [comment]
@jameslamb thank you for the question. I haven't been using `uptasticsearch` for long time since the moment, so, unfortunately, I couldn't add something extra to the report. If you want to close this issue I think it is a good idea for now. Last time when I have been using it everything was perfect.

**Comment by jameslamb** [comment]
Ok sounds good! Thanks again for taking the time to report originally and for getting back to me tonight.
